### ISSUE TITLE
Non-cluster weights

### ISSUE THREAD

**Issue by andrewjmc** [AnestisTouloumis/multgee#3]
Is it possible to use non-cluster weights (i.e. inverse probability weights) in ordLORgee? And if so, can robust standard errors still be produced?

Thanks,

Andrew

**Comment by AnestisTouloumis** [comment]
Not yet. I plan to implement this feature on a future version of multgee.

**Comment by andrewjmc** [comment]
OK, thanks Anestis, helpful to know!
