### ISSUE TITLE
About computation time using ordLORgee from multgee package

### ISSUE THREAD

**Issue by CharlieLiu220** [AnestisTouloumis/multgee#5]
Hi Dr. Touloumis,

My question is that it seems take forever to run ordLORgee for conducting correlated ordinal regression.

The setting is look at the effect of one intervention (binary) on an ordinal categorical outcome (around 10 levels). The correlation of outcomes comes from that different observations correspond to different physicians (defining clusters). It is not a longitudinal setting, where we don't have or don't care observations at different time points for the same cluster. But when uniform/exchangeable correlation structure is assumed, the longitudinal setting is similar to our cluster setting.

My code is like
`ordLORgee(Y~POI+X, data=data, id=id, LORstr = "uniform")`
, where POI is the predictor of interest, X represents covariates to adjust for, id is the index of cluster and the data is already sorted by the id.

Specifically, the sample size is around 150-200 and the number of cluster is around 10-15.

It took really long and took up much memory. I don't know what's going on. Is that because of non-convergence of the algorithm with respect to my data?

Best,
Charlie

**Comment by AnestisTouloumis** [comment]
It is very difficult to understand what exactly is going on without having reproducible code (i.e. in this case without having access to the data). It might worth using LORstr = "independence" and/or to reduce the levels of the categorical outcome.
